<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-90C26VK" ignored="2" name="Test" tests="2" failures="1" timestamp="28 Feb 2020 09:59:43 GMT" time="0.068" errors="0">
  <testcase name="thirdclass" time="0.015" classname="com.automation.testcases.Tc1_Login"/>
  <testcase name="secondclass" time="0.007" classname="com.automation.testcases.Tc1_Login">
    <failure type="java.lang.AssertionError" message="expected [not matching..so it will failed] but found [TestingFailed]">
      <![CDATA[java.lang.AssertionError: expected [not matching..so it will failed] but found [TestingFailed]
at com.automation.testcases.Tc1_Login.secondclass(Tc1_Login.java:80)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- secondclass -->
  <testcase name="fifithclass" time="0.0" classname="com.automation.testcases.Tc1_Login">
    <ignored/>
  </testcase> <!-- fifithclass -->
  <testcase name="fourthclass" time="0.0" classname="com.automation.testcases.Tc1_Login">
    <ignored/>
  </testcase> <!-- fourthclass -->
</testsuite> <!-- Test -->
